### ISSUE TITLE
WS(S) gateway

### ISSUE THREAD

**Issue by alekseiZh** [freeswitch/sofia-sip#225]
Is it possible to make gateway with WS(S) transport? I can't find any clear answer to this question. 

So I've tried to add "transport=wss" to outbound proxy address string. As I see in tcpdump traces, TCP connection is established during registration, but no data is transferred. Log says:

`tport_type_ws.c:331 tport_send_stream_ws() ws_write_frame: Resource temporarily unavailable (-56)`
After several attempts to get access to resource, registration fails with 408 code.

Source code investigation and recompilation with additional debug messages shows that calling SSL_write() function constantly leads to the error: SSL_ERROR_WANT_READ. I can't figure out if this problem is specific only to my system, or WSS transport is not supported at all in gateways configs.

**Comment by seven1240** [comment]
outbound wss transport is not supported yet.

**Comment by monishkumardurairaj** [comment]
When attempting a WebSocket client connection, the flow reaches:

tport_base_connect() → tport_alloc_secondary() → tport_ws_init_secondary() → WS_INIT() → establish_logical_layer() → ws_handshake()
Since ws_handshake() mainly processes incoming WebSocket requests, I expected the HTTP GET request for the client-side handshake to be constructed earlier, but I don’t see where that happens.

@seven1240 Is the issue is still present, that outbound call not supported?

**Comment by seven1240** [comment]
Not yet. I have had some experiment code but I don't know if it's really useful. why you want that? could you just use the TLS transport?

**Comment by alekseiZh** [comment]
It's definitely not a "must have" feature, but in my case, I've developed a testing tool designed to send calls to a SIP service that supports multiple transport protocols, including TCP, UDP, TLS, and WSS.

Another case to consider is a FS based softphone that supports multiple transport protocols.
